# Generated by Django 3.2.12 on 2022-03-26 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220326_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 26, 9, 49, 50, 571500, tzinfo=utc), null=True),
        ),
    ]
