# Generated by Django 3.2.12 on 2022-03-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baskets',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
    ]
