# Generated by Django 3.2.12 on 2022-04-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_alter_baskets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baskets',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'корзина'},
        ),
    ]
