# Generated by Django 3.2.12 on 2022-04-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('status', models.CharField(choices=[('1', 'формируется'), ('2', 'отправлен в обработку'), ('4', 'оплачен'), ('3', 'обрабатывается'), ('5', 'готов к выдаче'), ('6', 'отменен')], default='1', max_length=3, verbose_name='статус')),
                ('country', models.CharField(choices=[('1', 'Россия')], default='1', max_length=3, verbose_name='страна')),
                ('region', models.CharField(choices=[('1', 'Московская область'), ('2', 'Ростовская область'), ('3', 'Краснодарский край')], default='1', max_length=3, verbose_name='регион')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('index', models.CharField(max_length=6, verbose_name='индекс')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='элемент заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт')),
            ],
        ),
    ]
