# Generated by Django 3.2.12 on 2022-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('1', 'Россия')], default='1', max_length=3, verbose_name='страна'),
        ),
    ]
