# Generated by Django 3.2.12 on 2022-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220326_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Есть', 'Есть в наличии'), ('Нет', 'Нет в наличии')], default='Есть в наличии', max_length=20, verbose_name='Наличие товара'),
        ),
    ]
